config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
  get 'home', to: 'home#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :category
  belongs_to :member
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	enum role: {:full_access => 0, :restricted_access => 1}

	#scopes
	scope :with_full_access, -> {where(role: 0)}
	scope :with_restricted_access, -> {where(role: 1)}

	def self.with_full_access
		where(role: 'full_access')
	end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :description
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
	#pundit
	include Pundit

	#Manages Pundit Errors
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

    # Layout per resource_name
	layout :layout_by_resource

  	protected

	def layout_by_resource
	  if devise_controller? && resource_name == :admin
	    "backoffice_devise"
	  else
	    "application"
	  end
	end

	def user_not_authorized
    	flash[:alert] = "Você não está autorizado a executar esta ação!"
    	redirect_to(request.referrer || root_path)
  	end

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
  	#@admins = Admin.with_full_access
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save 
      redirect_to backoffice_admins_path, notice: I18n.t('messages.created_with', item: @admin.name)
    else
      render :new
    end
  end

  def edit
  end

  def update
     if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
       redirect_to backoffice_admins_path, notice: I18n.t('messages.updated_with', item: @admin.name)
      else
       render :edit
     end
  end

  def destroy
    authorize @admin
    admin_name = @admin.name

    if @admin.destroy
      redirect_to backoffice_admins_path, notice: I18n.t('messages.destroyed_with', item: admin_name)
    else
      render :edit
    end  
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end
  
  def params_admin 
   passwd = params[:admin][:password]
   passwd_confirmation = params[:admin][:password_confirmation]

   if passwd.blank? && passwd_confirmation.blank?
     params[:admin].delete(:password)
     params[:admin].delete(:password_confirmation)
   end
    params.require(:admin).permit(policy(@admin).permitted_attributes)
  end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]


  def index
  	@categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)

    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: I18n.t('messages.created_with', item: @category.description)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: I18n.t('messages.updated_with', item: @category.description)
    else
      render :edit
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end
  
  def params_category 
    params.require(:category).permit(:description)
  end

end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
	attr_accessor :category

	def self.create(params_category)
		@category = Category.new(params_category)

		if @category.valid?
			@category.save!
		end

		@category
	end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  	# render app/views/backoffice/dashboard/index.html.erb
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
  	current_admin	# current_user to pundit
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
	layout "site"
  def index
  	@categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

	OptionsForRoles = Struct.new(:id,:description)


	def options_for_roles

		Admin.roles_i18n.map do |key, value|
			OptionsForRoles.new(key,value)
		end
	end

end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form",
			locals: {action_message: t('messages.editing', model: @admin.model_name.human)} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= @admins.model_name.human(count: 2) %></h1>
 
 <div class="panel panel-default">
     <div class="panel-heading">
         <%= t('messages.listing', model: @admins.model_name.human(count: 2)) %>
         
        <% if policy(@admins).new? %>
            <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
                <i class="fa fa-plus"></i>
            <% end %>

        <% end -%>
     </div>
     <!-- /.panel-heading -->
     <div class="panel-body">
         <div class="table-responsive">
             <table class="table table-striped table-bordered table-hover">
                 <thead>
                     <tr>
                         <th>#</th>
                         <th><%= @admins.model.human_attribute_name('name') %></th>
                         <th><%= @admins.model.human_attribute_name('email') %></th>
                         <th><%= @admins.model.human_attribute_name('role') %></th>
                         <th></th>
                     </tr>
                 </thead>
                 <tbody>
                     <% @admins.each do |admin| %>
                     <tr>
                         <td><%= admin.id %></td>
                         <td><%= admin.name %></td>
                         <td><%= admin.email %></td>
                         <td><%= admin.role_i18n %></td>
                         <td style="width: 150px">
                             <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                                 <i class="fa fa-edit"></i>
                             <% end %>

                             <% if current_admin.id != admin.id &&  policy(@admins).destroy?%>
	                             <%= link_to backoffice_admin_path(admin), method: :delete, class:"btn btn-danger btn-circle", data: {confirm: t('messages.confirm_with', item: admin.name)} do %>
	                             <i class="fa fa-minus"></i>
	                             <% end -%>
                             <%else%>
	                             <%= link_to "#", disabled: 'disabled', class:"btn btn-danger btn-circle" do %>
		                             <i class="fa fa-minus"></i>
		                     		 <% end -%>
		                     <% end -%>
                         </td>
                     </tr>
                     <% end %>
                 </tbody>
             </table>
         </div>
         <!-- /.table-responsive -->
     </div>
     <!-- /.panel-body -->
 </div>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form",
			locals: {action_message: t('messages.new', model: @admin.model_name.human)} %>

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header"><%= @admin.model_name.human(count: 2) %></h1>
 
 <% if @admin.errors.any? %>
     <div class="alert alert-danger alert-dismissable">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
 
     <ul>
         <% @admin.errors.full_messages.each do |message| %>
             <li><%= message %></li>
         <% end %>
     </ul>
 
     </div>
 <% end %>
 
 <div class="panel panel-default">
     <div class="panel-heading">
         <%= action_message%>
     </div>
     <!-- /.panel-heading -->
     <div class="panel-body">
         <div class="col-lg-6">
             <%= form_for([:backoffice, @admin]) do |f| %>
                 <div class="form-group">
                     <%= f.label :name %>
                     <%= f.text_field :name, class:"form-control", placeholder:"Nome do administrador" %>
 
                 </div>
                 <div class="form-group">
                     <%= f.label :email %>
                     <%= f.text_field :email, class:"form-control", placeholder:"Email do administrador" %>
 
                 </div>

                <% if policy(@admin).edit? %>
                     <div class="form-group">
                        <%= f.label :role %> <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
                            <div class="radio">
                                <%= b.label { b.radio_button + b.text} %>
                            </div>
                        <% end %>
                     </div>
                 <% end -%>

                 <div class="form-group">
                     <%= f.label :password %>
                     <%= f.password_field :password, class:"form-control", placeholder:"Senha" %>
 
                 </div>
                 <div class="form-group">
                     <%= f.label :password_confirmation %>
                     <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da senha" %>
 
                 </div>
 
                 <button type="submit" class="btn btn-default">Salvar</button>
             <% end %>
         </div>
     </div>
     <!-- /.panel-body -->
 </div>

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", 
    locals: {action_message: t('messages.editing', model: @category.model_name.human)} %>

app/views/backoffice/categories/index.html.erb
<h1 class="page-header"><%= @categories.model_name.human(count: 2) %></h1>

 <div class="panel panel-default">
    <div class="panel-heading">
        <%= t('messages.listing', model: @categories.model_name.human(count: 2)) %>
        <%= link_to new_backoffice_category_path, class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px" do %>
            <i class="fa fa-plus"></i>
        <% end -%>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><%= @categories.model.human_attribute_name('description') %></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.id %></td>
                        <td><%= category.description %></td>
                        <td style="width: 150px">
                            <%= link_to edit_backoffice_category_path(category), class: "btn btn-primary btn-circle" do %>
                            <i class="fa fa-edit"></i>
                            <% end -%>


                            <button type="button" disabled="disabled" class="btn btn-danger btn-circle"><i class="fa fa-minus"></i>
                            </button>
                    </td>
                    </tr>
                    <% end -%>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", 
    locals: {action_message: t('messages.new', model: @category.model_name.human)} %>

app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escamboapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BackOffice - Escamboapp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
 	<%= stylesheet_link_tag    'backoffice', media: 'all' %>
  
  	<%= javascript_include_tag 'application' %>
  	<%= javascript_include_tag 'backoffice' %>

	<%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
        <%= render partial: "layouts/backoffice_shared/navigation" %>
        
        <!-- Page Content -->   
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <% if notice %>
        <script>
            $.notify("<%= notice %>", "sucess");
        </script>
    <% end -%>

    <% if alert %>
    <script>
        $.notify("<%= alert %>", "error");
    </script>
    <% end -%>
</body>
</html>

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BackOffice - Escamboapp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 	<%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>
  
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

    <body>
        	<%= yield %>
    </body>

    </html>

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">BackOffice</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li><%= current_admin.name %></li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <%= link_to destroy_admin_session_path, method: :delete do %>
                                <i class="fa fa-sign-out fa-fw"></i> Sair
                            <% end -%>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <%= link_to backoffice_path do %>
                            <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <% end -%>
                        </li>
                        <li>
                            <%= link_to backoffice_categories_path do %>
                                <i class="fa fa-th-list fa-fw"></i> Categorias
                            <% end -%>
                        </li>
                        <li>
                            <%= link_to backoffice_admins_path do %>
                                <i class="fa fa-users fa-fw"></i> Administradores
                            <% end -%>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EscamboApp</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track' => true %>

  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'site', 'data-turbolinks-track' => true %>
  	
  	<%= csrf_meta_tags %>



  </head>

  <body>
    <%= render partial: "layouts/site_shared/navigation" %>
	  <%= yield %>
    <%= render partial: "layouts/site_shared/footer" %>
  </body>

</html>

app/views/layouts/site_shared/_footer.html.erb
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/site/home/index.html.erb
    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h1 class="my-4">Categorias</h1>
          <div class="list-group">
            <% @categories.each do |category|%>
            <a href="#" class="list-group-item"><%= category.description %></a>
            <% end -%>
          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

          <div class="row">

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item One</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Two</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Three</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Four</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Five</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Six</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

          </div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>